baseURL = "https://karthikraobr.github.io/"
languageCode = "en-us"
title = "Gibberish"
theme = "beautifulhugo"
author = "Kaarthik"
copyright = "Â© Copyright 2018"
googleAnalytics="UA-112060036-1"
disqusShortname = "https-karthikraobr-github-io"


[Params]
UseChroma = true
  subtitle = "Kaarthik's Blog"
  logo = "img/profile.jpg"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true

  [Author]
  name = "Kaarthik"
  email = "karthik.0703@gmail.com"
  facebook = "karthik.0703"
  googleplus = "+KarthikRao7"
  github = "karthikraobr"
  twitter = "karthikraobr"
  linkedin = "karthikraobr"
  stackoverflow = "/users/1309509/geekboy"
  instagram = "karthikraobr"

  [[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 2

[[menu.main]]
    name = "Resume"
    url = "page/resume"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 4

[[menu.main]]
    name = "Categories"
    url = "/categories"
    weight = 4
