baseURL = "https://kaarthik.dev"
languageCode = "en-us"
title = "Gibberish"
theme = "fuji"
googleAnalytics="UA-112060036-1"

showLicense = false # Enable or disable license for all post
showToc = false # Enable or disable ToC for all post



[Params]
  UseChroma = true
  subtitle = "Kaarthik's musings"
  logo = "img/profile.jpg"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  socialShare = true
  author = "Kaarthik"
  showWordCounter = true
  showReadTime = true
  disqusShortname = "https-karthikraobr-github-io"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Enable user to embed HTML snippets in Markdown content

[menu]
    [[menu.nav]]
        name = "Home"
        url = "/"
        weight = 1

    [[menu.nav]]
        name = "About"
        url = "/page/about"
        weight = 2

    [[menu.nav]]
        name = "Résumé"
        url = "/page/resume"
        weight = 3


  [[menu.link]]
    name = "GitHub"
    url = "https://github.com/karthikraobr"
    weight = 1
  [[menu.link]]
    name = "Twitter"
    url = "https://twitter.com/karthikraobr"
    weight = 2
  [[menu.link]]
    name = "Linkedin"
    url = "https://www.linkedin.com/in/karthikraobr/"
    weight = 3
  [[menu.link]]
    name = "Email"
    url = "mailto:hi@kaarthik.dev"
    weight = 4